server:
  port: 10012

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  instance:
    preferIpAddress: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5

management:
  security:
    enabled: false

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3308/investdb
    username: root
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10100/eureka/

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mariadb:3308/investdb

eureka:
  client:
    serviceUrl:
      defaultZone: http://discoery-service:10100/eureka/